src/HodHod.Web.Mvc/Areas/App/Models/Users/CreateOrEditUserModalViewModel.cs
using System.Linq;
using Abp.Authorization.Users;
using Abp.AutoMapper;
using HodHod.Authorization.Users.Dto;
using HodHod.Security;
using HodHod.Web.Areas.App.Models.Common;

namespace HodHod.Web.Areas.App.Models.Users;

[AutoMapFrom(typeof(GetUserForEditOutput))]
public class CreateOrEditUserModalViewModel : GetUserForEditOutput, IOrganizationUnitsEditViewModel
{
    public bool CanChangeUserName => User.UserName != AbpUserBase.AdminUserName;

    public int AssignedRoleCount
    {
        get { return Roles.Count(r => r.IsAssigned); }
    }

    public int AssignedOrganizationUnitCount => MemberedOrganizationUnits.Count;

    public bool IsEditMode => User.Id.HasValue;

    public PasswordComplexitySetting PasswordComplexitySetting { get; set; }
}

src/HodHod.Web.Mvc/Areas/App/Models/Users/UserExportExcelViewModel.cs
using System.Collections.Generic;

namespace HodHod.Web.Areas.App.Models.Users;

public class UserExportExcelViewModel
{
    public List<string> UserExcelColumns { get; set; }
}

src/HodHod.Web.Mvc/Areas/App/Models/Users/UserLoginAttemptsViewModel.cs
using System.Collections.Generic;
using Abp.Application.Services.Dto;

namespace HodHod.Web.Areas.App.Models.Users;

public class UserLoginAttemptsViewModel
{
    public List<ComboboxItemDto> LoginAttemptResults { get; set; }
}

src/HodHod.Web.Mvc/Areas/App/Models/Users/UserPermissionsEditViewModel.cs
using Abp.AutoMapper;
using HodHod.Authorization.Users;
using HodHod.Authorization.Users.Dto;
using HodHod.Web.Areas.App.Models.Common;

namespace HodHod.Web.Areas.App.Models.Users;

[AutoMapFrom(typeof(GetUserPermissionsForEditOutput))]
public class UserPermissionsEditViewModel : GetUserPermissionsForEditOutput, IPermissionsEditViewModel
{
    public User User { get; set; }
}

src/HodHod.Web.Mvc/Areas/App/Models/Users/UsersViewModel.cs
using System.Collections.Generic;
using Abp.Application.Services.Dto;
using HodHod.Authorization.Permissions.Dto;
using HodHod.Web.Areas.App.Models.Common;

namespace HodHod.Web.Areas.App.Models.Users;

public class UsersViewModel : IPermissionsEditViewModel
{
    public string FilterText { get; set; }

    public List<ComboboxItemDto> Roles { get; set; }

    public bool OnlyLockedUsers { get; set; }

    public List<FlatPermissionDto> Permissions { get; set; }

    public List<string> GrantedPermissionNames { get; set; }
}

src/HodHod.Web.Mvc/Areas/App/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Abp.Application.Services.Dto;
using Abp.AspNetCore.Mvc.Authorization;
using Abp.Authorization;
using Abp.BackgroundJobs;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using HodHod.Authorization;
using HodHod.Authorization.Permissions;
using HodHod.Authorization.Permissions.Dto;
using HodHod.Authorization.Roles;
using HodHod.Authorization.Roles.Dto;
using HodHod.Authorization.Users;
using HodHod.Authorization.Users.Importing;
using HodHod.DataImporting.Excel;
using HodHod.Security;
using HodHod.Storage;
using HodHod.Storage.FileValidator;
using HodHod.Web.Areas.App.Models.Users;
using HodHod.Web.Controllers;

namespace HodHod.Web.Areas.App.Controllers;

[Area("App")]
[AbpMvcAuthorize]
public class UsersController : ExcelImportControllerBase
{
    private readonly IUserAppService _userAppService;
    private readonly UserManager _userManager;
    private readonly IRoleAppService _roleAppService;
    private readonly IPermissionAppService _permissionAppService;
    private readonly IPasswordComplexitySettingStore _passwordComplexitySettingStore;
    private readonly IOptions<UserOptions> _userOptions;

    public override string ImportExcelPermission => AppPermissions.Pages_Administration_Users_Create;

    public UsersController(
        IUserAppService userAppService,
        UserManager userManager,
        IRoleAppService roleAppService,
        IPermissionAppService permissionAppService,
        IPasswordComplexitySettingStore passwordComplexitySettingStore,
        IOptions<UserOptions> userOptions,
        IBinaryObjectManager binaryObjectManager,
        IBackgroundJobManager backgroundJobManager,
        IFileValidatorManager fileValidatorManager
    ) : base(binaryObjectManager, backgroundJobManager, fileValidatorManager)
    {
        _userAppService = userAppService;
        _userManager = userManager;
        _roleAppService = roleAppService;
        _permissionAppService = permissionAppService;
        _passwordComplexitySettingStore = passwordComplexitySettingStore;
        _userOptions = userOptions;
    }

    [AbpMvcAuthorize(AppPermissions.Pages_Administration_Users)]
    public async Task<ActionResult> Index()
    {
        var roles = new List<ComboboxItemDto>();

        if (await IsGrantedAsync(AppPermissions.Pages_Administration_Roles))
        {
            var getRolesOutput = await _roleAppService.GetRoles(new GetRolesInput());
            roles = getRolesOutput.Items.Select(r => new ComboboxItemDto(r.Id.ToString(), r.DisplayName)).ToList();
        }

        roles.Insert(0, new ComboboxItemDto("", L("FilterByRole")));

        var permissions = _permissionAppService.GetAllPermissions().Items.ToList();

        var model = new UsersViewModel
        {
            FilterText = Request.Query["filterText"],
            Roles = roles,
            Permissions = ObjectMapper.Map<List<FlatPermissionDto>>(permissions).OrderBy(p => p.DisplayName)
                .ToList(),
            OnlyLockedUsers = false
        };

        return View(model);
    }

    [AbpMvcAuthorize(
        AppPermissions.Pages_Administration_Users,
        AppPermissions.Pages_Administration_Users_Create,
        AppPermissions.Pages_Administration_Users_Edit
    )]
    public async Task<PartialViewResult> CreateOrEditModal(long? id)
    {
        var output = await _userAppService.GetUserForEdit(new NullableIdDto<long> { Id = id });
        var viewModel = ObjectMapper.Map<CreateOrEditUserModalViewModel>(output);
        viewModel.PasswordComplexitySetting = await _passwordComplexitySettingStore.GetSettingsAsync();
        viewModel.AllowedUserNameCharacters = _userOptions.Value.AllowedUserNameCharacters;

        return PartialView("_CreateOrEditModal", viewModel);
    }

    [AbpMvcAuthorize(
        AppPermissions.Pages_Administration_Users,
        AppPermissions.Pages_Administration_Users_ChangePermissions
    )]
    public async Task<PartialViewResult> PermissionsModal(long id)
    {
        var output = await _userAppService.GetUserPermissionsForEdit(new EntityDto<long>(id));
        var viewModel = ObjectMapper.Map<UserPermissionsEditViewModel>(output);
        viewModel.User = await _userManager.GetUserByIdAsync(id);
        ;
        return PartialView("_PermissionsModal", viewModel);
    }

    public async Task<PartialViewResult> ExcelExportModal(long? id)
    {
        var output = await _userAppService.GetUserExcelColumnsToExcel();
        var viewModel = new UserExportExcelViewModel
        {
            UserExcelColumns = output
        };

        return PartialView("_ExportExcelModal", viewModel);
    }

    public ActionResult LoginAttempts()
    {
        var loginResultTypes = Enum.GetNames(typeof(AbpLoginResultType))
            .Select(e => new ComboboxItemDto(e, L("AbpLoginResultType_" + e)))
            .ToList();

        loginResultTypes.Insert(0, new ComboboxItemDto("", L("All")));

        return View("LoginAttempts", new UserLoginAttemptsViewModel()
        {
            LoginAttemptResults = loginResultTypes
        });
    }

    public override async Task EnqueueExcelImportJobAsync(ImportFromExcelJobArgs args)
    {
        await BackgroundJobManager.EnqueueAsync<ImportUsersToExcelJob, ImportFromExcelJobArgs>(args);
    }
}

src/HodHod.Web.Mvc/Controllers/ProfileController.cs
using Abp.AspNetCore.Mvc.Authorization;
using Abp.AspNetZeroCore.Net;
using Abp.Auditing;
using Abp.Extensions;
using Microsoft.AspNetCore.Mvc;
using HodHod.Authorization.Users.Profile;
using HodHod.Authorization.Users.Profile.Dto;
using HodHod.Storage;
using System;
using System.Threading.Tasks;

namespace HodHod.Web.Controllers;

[AbpMvcAuthorize]
[DisableAuditing]
public class ProfileController : ProfileControllerBase
{
    private readonly IProfileAppService _profileAppService;
    public ProfileController(
        ITempFileCacheManager tempFileCacheManager,
        IProfileAppService profileAppService)
        : base(tempFileCacheManager, profileAppService)
    {
        _profileAppService = profileAppService;
    }

    public async Task<FileResult> GetProfilePicture()
    {
        var output = await _profileAppService.GetProfilePicture();

        if (output.ProfilePicture.IsNullOrEmpty())
        {
            return GetDefaultProfilePictureInternal();
        }

        return File(Convert.FromBase64String(output.ProfilePicture), MimeTypeNames.ImageJpeg);
    }

    public virtual async Task<FileResult> GetFriendProfilePicture(long userId, int? tenantId)
    {
        var output = await _profileAppService.GetFriendProfilePicture(new GetFriendProfilePictureInput()
        {
            TenantId = tenantId,
            UserId = userId
        });

        if (output.ProfilePicture.IsNullOrEmpty())
        {
            return GetDefaultProfilePictureInternal();
        }

        return File(Convert.FromBase64String(output.ProfilePicture), MimeTypeNames.ImageJpeg);
    }
}

src/HodHod.Web.Mvc/Areas/App/Views/Users/LoginAttempts.cshtml
@using HodHod.Web.Areas.App.Models.Users
@using Abp.Application.Services.Dto
@model UserLoginAttemptsViewModel

@section Scripts
{
    <script abp-src="/view-resources/Areas/App/Views/Users/LoginAttempts.js" asp-append-version="true"></script>
}

<abp-page-subheader title="@L("LoginAttempts")" description="@L("LoginAttemptsHeaderInfo")">
</abp-page-subheader>

<div class="@(await GetContainerClass())">
    <div class="card">
        <div class="card-body">
            <div class="form">
                <div class="row align-items-center mb-4">
                    <div class="col-md-12">
                        <div class="mb-5">
                            <label for="LoginAttemptsFilter" class="form-label">@L("Filter")</label>
                            <div class="input-group">
                                <input type="text" id="LoginAttemptsFilter" class="form-control" placeholder="@L("SearchWithThreeDot")" value="">
                                <button id="GetLoginAttemptsButton" class="btn btn-primary" type="submit">
                                    <i class="flaticon-search-1" aria-label="@L("Search")"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row align-items-center mb-4">
                    <div class="col-md-6">
                        <div class="mb-5">
                            <label for="StartEndRange" class="form-label">@L("DateRange")</label>
                            <input id="StartEndRange" type="text" class="form-control date-range-picker"/>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="mb-5">
                            <label for="LoginResultFilter" class="form-label">@L("Result")</label>
                            @Html.DropDownList("LoginResultFilter", Model.LoginAttemptResults.Select(e => e.ToSelectListItem()), new {@class = "form-select", id = "LoginResultFilter"})
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mb-3 mt-5">
                <div class="col-sm-12 text-end">
                    <button id="RefreshLoginAttempts" class="btn btn-primary">
                        <i class="la la-refresh btn-md-icon"></i>
                        <span class="d-none d-md-inline-block">
                            @L("Refresh")
                        </span>
                    </button>
                </div>
            </div>
            <div class="align-items-center">
                <table id="LoginAttemptsTable" class="table align-middle table-row-dashed fs-6 gy-5 dataTable dtr-inline no-footer" width="100%">
                    <thead>
                    <tr>
                        <th>@L("IpAddress")</th>
                        <th>@L("Client")</th>
                        <th>@L("Browser")</th>
                        <th>@L("Time")</th>
                        <th>@L("Result")</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

src/HodHod.Web.Mvc/Areas/App/Views/Users/_CreateOrEditModal.cshtml
@using Abp.Authorization.Users
@using Abp.Configuration
@using Abp.Json
@using Abp.Zero.Configuration
@using HodHod.Authorization
@using HodHod.Authorization.Users
@using HodHod.Net.Emailing
@using HodHod.Web.Areas.App.Models.Common.Modals
@using HodHod.Web.Areas.App.Models.Users
@model CreateOrEditUserModalViewModel
@inject IEmailSettingsChecker EmailSettingsChecker

@{
    var isSMTPSettingsProvided = await EmailSettingsChecker.EmailSettingsValidAsync();
}
<script>
    window.passwordComplexitySetting = @Html.Raw(Model.PasswordComplexitySetting.ToJsonString(indented: true));
</script>
@await Html.PartialAsync("~/Areas/App/Views/Common/Modals/_ModalHeader.cshtml", new ModalHeaderViewModel(Model.IsEditMode ? (L("EditUser") + ": " + Model.User.UserName) : L("CreateNewUser")))

<div class="modal-body user-edit-modal">
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a href="#UserInformationsTab" class="nav-link active" data-bs-toggle="tab" role="tab">
                @L("UserInformations")
            </a>
        </li>
        <li class="nav-item">
            <a href="#RolesTab" data-bs-toggle="tab" role="tab" class="nav-link">
                @L("Roles") <span id="assigned-role-count" class="badge badge-success me-2">@Model.AssignedRoleCount</span>
            </a>
        </li>
        <li class="nav-item">
            <a href="#OrganizationUnitsTab" data-bs-toggle="tab" role="tab" class="nav-link">
                @L("OrganizationUnits") <span id="assigned-organization-unit-count" class="badge badge-success me-2">@Model.AssignedOrganizationUnitCount</span>
            </a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane pt-5 active" id="UserInformationsTab" role="tabpanel">
            <form name="UserInformationsForm" role="form" novalidate class="form-validation">

                @if (Model.IsEditMode)
                {
                    <input type="hidden" name="Id" value="@Model.User.Id"/>
                }

                <div class="row">
                    <div class="col-sm-3 text-center margin-top-15 margin-bottom-15">
                        @if (Model.User.Id > 0)
                        {
                            <img src="@Url.Action("GetProfilePictureByUser", "Profile", new { area = string.Empty })?userId=@(Model.User.Id)&&profilePictureId=@(Model.ProfilePictureId)" width="128" height="128" class="img-thumbnail img-rounded user-edit-dialog-profile-image"/>
                        }
                        else
                        {
                            <img src="@Url.Content($"{ApplicationPath}Common/Images/default-profile-picture.png")" width="128" height="128" class="img-thumbnail img-rounded user-edit-dialog-profile-image"/>
                        }
                        
                        @if(Model.User.Id > 0 && await PermissionChecker.IsGrantedAsync(AppPermissions.Pages_Administration_Users_ChangeProfilePicture)){
                            <button class="btn btn-light btn-sm mb-5" id="changeProfilePicture">@L("ChangeProfilePicture")</button>
                        }
                    </div>
                    <div class="col-sm-9">
                        <div class="mb-5">
                            <label for="Name" class="form-label required">@L("FirstName")</label>
                            <input id="Name" class="form-control" value="@Model.User.Name" type="text" name="Name" required maxlength="@HodHod.Authorization.Users.User.MaxNameLength">
                        </div>

                        <div class="mb-5">
                            <label for="Surname" class="form-label required">@L("Surname")</label>
                            <input id="Surname" type="text" name="Surname" class="form-control" value="@Model.User.Surname" required maxlength="@HodHod.Authorization.Users.User.MaxSurnameLength">
                        </div>
                    </div>
                </div>

                <div class="mb-5">
                    <label for="EmailAddress" class="form-label required">@L("EmailAddress")</label>
                    <input id="EmailAddress" type="email" name="EmailAddress" class="form-control" value="@Model.User.EmailAddress" required maxlength="@AbpUserBase.MaxEmailAddressLength">
                </div>

                <div class="mb-5">
                    <label for="PhoneNumber" class="form-label">@L("PhoneNumber")</label>
                    <input id="PhoneNumber" type="text" name="PhoneNumber" class="form-control" value="@Model.User.PhoneNumber" maxlength="@UserConsts.MaxPhoneNumberLength">
                </div>

                <div class="mb-5 form-md-line-input form-md-floating-label">
                    <label for="UserName" class="form-label required">@L("UserName")</label>
                    <div class="input-group">
                        <input id="UserName" type="text" @Html.Raw(!Model.CanChangeUserName ? "disabled=\"disabled\"" : "") name="UserName" class="form-control" value="@Model.User.UserName" required maxlength="@AbpUserBase.MaxUserNameLength">
                        <span class="input-group-text" data-bs-toggle="tooltip" data-bs-placement="right" title="@L("AllowedUserNameCharactersInfoText", Model.AllowedUserNameCharacters)">
                            <i class="fas fa-info-circle"></i>
                        </span>
                    </div>
                    @if (!Model.CanChangeUserName)
                    {
                        <span class="form-text text-muted">@L("CanNotChangeAdminUserName")</span>
                    }
                </div>

                <div class="checkbox-list mb-3">
                    <label for="EditUser_SetRandomPassword" class="form-check form-check-custom form-check-solid">
                        <input id="EditUser_SetRandomPassword" type="checkbox" name="SetRandomPassword" class="form-check-input" value="true" @Html.Raw(Model.IsEditMode ? "" : "checked=\"checked\"")/>
                        <span class="form-check-label">
                            @L("SetRandomPassword")
                        </span>
                    </label>
                </div>

                <div class="mb-5 user-password" style="@(Model.IsEditMode ? "display:block" : "display:none")" data-kt-password-meter="true">
                    <label for="EditUser_Password" class="form-label">@L("Password")</label>
                    <div class="position-relative mb-3">
                        <input id="EditUser_Password" type="password" name="Password" class="form-control auto-complete-off"
                               maxlength="@HodHod.Authorization.Users.User.MaxPlainPasswordLength" autocomplete="new-password">
                        
                        <!--begin::Visibility toggle-->
                        <span class="btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2"
                              data-kt-password-meter-control="visibility">
                            <i class="fas fa-eye-slash fs-4"><span class="path1"></span><span class="path2"></span><span class="path3"></span><span class="path4"></span></i>
                            <i class="fas fa-eye d-none fs-4"><span class="path1"></span><span class="path2"></span><span class="path3"></span></i>
                        </span>
                        <!--end::Visibility toggle-->
                    </div>
                </div>
                
                <div class="mb-5 user-password" style="@(Model.IsEditMode ? "display:block" : "display:none")" data-kt-password-meter="true">
                    <label for="PasswordRepeat" class="form-label">@L("PasswordRepeat")</label>
                    <div class="position-relative mb-3">
                        <!--begin::Visibility toggle-->
                        <span class="btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2"
                              data-kt-password-meter-control="visibility">
                            <i class="fas fa-eye-slash fs-4"><span class="path1"></span><span class="path2"></span><span class="path3"></span><span class="path4"></span></i>
                            <i class="fas fa-eye d-none fs-4"><span class="path1"></span><span class="path2"></span><span class="path3"></span></i>
                        </span>
                        <!--end::Visibility toggle-->
                        <input id="PasswordRepeat" type="password" name="PasswordRepeat" class="form-control auto-complete-off" readonly onfocus="this.removeAttribute('readonly');"
                               maxlength="@HodHod.Authorization.Users.User.MaxPlainPasswordLength" equalto="#EditUser_Password" autocomplete="new-password">
                    </div>
                </div>

                <div class="checkbox-list">
                    <label for="EditUser_ShouldChangePasswordOnNextLogin" class="form-check form-check-custom form-check-solid mb-2">
                        <input id="EditUser_ShouldChangePasswordOnNextLogin" type="checkbox" name="ShouldChangePasswordOnNextLogin" class="form-check-input" value="true" @Html.Raw(Model.User.ShouldChangePasswordOnNextLogin ? "checked=\"checked\"" : "")>
                        <span class="form-check-label">
                            @L("ShouldChangePasswordOnNextLogin")
                        </span>
                    </label>

                    @if (!isSMTPSettingsProvided)
                    {
                        <span class="form-text text-muted">@L("SMTPSettingsNotProvidedWarningText")</span>
                    }

                    <label for="EditUser_SendActivationEmail" class="form-check form-check-custom form-check-solid mb-2">
                        <input id="EditUser_SendActivationEmail" type="checkbox" name="SendActivationEmail" class="form-check-input" value="true" @(!isSMTPSettingsProvided ? "disabled='disabled'" : "") @Html.Raw(Model.IsEditMode || !isSMTPSettingsProvided ? "" : "checked=\"checked\"")>
                        <span class="form-check-label">
                            @L("SendActivationEmail")
                        </span>
                    </label>

                    <label for="EditUser_IsActive" class="form-check form-check-custom form-check-solid mb-2">
                        <input id="EditUser_IsActive" type="checkbox" name="IsActive" class="form-check-input" value="true" @Html.Raw(Model.User.IsActive ? "checked=\"checked\"" : "")>
                        <span class="form-check-label">
                            @L("Active")
                        </span>
                    </label>
                    @if (SettingManager.GetSettingValue<bool>(AbpZeroSettingNames.UserManagement.TwoFactorLogin.IsEnabled))
                    {
                        <label for="EditUser_IsTwoFactorEnabled" class="form-check form-check-custom form-check-solid mb-2">
                            <input id="EditUser_IsTwoFactorEnabled" type="checkbox" name="IsTwoFactorEnabled" class="form-check-input" value="true" @Html.Raw(Model.User.IsTwoFactorEnabled ? "checked=\"checked\"" : "")>
                            <span class="form-check-label">
                                @L("IsTwoFactorEnabled")
                            </span>
                        </label>
                    }
                    @if (SettingManager.GetSettingValue<bool>(AbpZeroSettingNames.UserManagement.UserLockOut.IsEnabled))
                    {
                        <label for="EditUser_IsLockoutEnabled" class="form-check form-check-custom form-check-solid mb-2">
                            <input id="EditUser_IsLockoutEnabled" type="checkbox" name="IsLockoutEnabled" class="form-check-input" value="true" @Html.Raw(Model.User.IsLockoutEnabled ? "checked=\"checked\"" : "")>
                            <span class="form-check-label">
                                @L("IsLockoutEnabled")
                            </span>
                            <i class="fas fa-info-circle ms-2" data-bs-toggle="tooltip" title="@L("IsLockoutEnabled_Hint")"></i>
                        </label>
                    }
                </div>

            </form>
        </div>
        <div class="tab-pane pt-5" id="RolesTab" role="tabpanel">
            <div class="user-role-checkbox-list">
                @foreach (var role in Model.Roles)
                {
                    <div class="checkbox-list pb-1">
                        <label for="EditUser_@(role.RoleName)" class="form-check form-check-custom form-check-solid mb-2">
                            <input id="EditUser_@(role.RoleName)"
                                   type="checkbox"
                                   name="@(role.RoleName)"
                                   class="form-check-input"
                                   value="true"
                                   @Html.Raw(role.IsAssigned ? "checked=\"checked\"" : "")
                                   @Html.Raw(role.InheritedFromOrganizationUnit ? "disabled=\"disabled\"" : "")>
                            <span class="form-check-label">
                                @role.RoleDisplayName
                                @if (role.InheritedFromOrganizationUnit)
                                {
                                    <small>(@L("RoleIsInheritedFromOrganizationUnit"))</small>
                                }
                            </span>
                        </label>
                    </div>
                }
            </div>
        </div>
        <div class="tab-pane pt-5" id="OrganizationUnitsTab" role="tabpanel">
            <div class="list-group">
                @await Html.PartialAsync("~/Areas/App/Views/Common/_OrganizationTree.cshtml", Model)
            </div>
        </div>
    </div>
</div>

@await Html.PartialAsync("~/Areas/App/Views/Common/Modals/_ModalFooterWithSaveAndCancel.cshtml")

src/HodHod.Web.Mvc/Areas/App/Views/Users/_ExportExcelModal.cshtml
@using HodHod.Web.Areas.App.Models.Common.Modals
@using HodHod.Web.Areas.App.Models.Users
@model UserExportExcelViewModel

@await Html.PartialAsync("~/Areas/App/Views/Common/Modals/_ModalHeader.cshtml", new ModalHeaderViewModel(L("ChooseColumnsForExcelExport")))

<div class="modal-body">
  <form>
    <div class="d-flex justify-content-between">
      <h2>@L("Columns")</h2>
      <button id="btnToggleAll" class="btn btn-primary btn-sm mb-5">@L("SelectAll")</button>
    </div>
    @for (var i = 0; i < Model.UserExcelColumns.Count; i++)
    {
      var userColumn = "userColumn" + i;

      <div class="form-check mb-3">
        <input class="form-check-input" type="checkbox" value="@Model.UserExcelColumns[i]" id="@userColumn">
        <label class="form-check-label" for="@userColumn">
          @Model.UserExcelColumns[i]
        </label>
      </div>
    }
  </form>
</div>

<div class="modal-footer">
  <button type="button" class="btn btn-light-primary fw-bold close-button" data-bs-dismiss="modal">@L("Cancel")</button>
  <button type="button" class="btn btn-primary save-button"><i class="fa fa-save"></i> <span>@L("ExportExcel")</span></button>
</div>

src/HodHod.Web.Mvc/Areas/App/Views/Users/_PermissionsModal.cshtml
@using HodHod.Web.Areas.App.Models.Common.Modals
@using HodHod.Web.Areas.App.Models.Users
@model UserPermissionsEditViewModel

@await Html.PartialAsync("~/Areas/App/Views/Common/Modals/_ModalHeader.cshtml", new ModalHeaderViewModel(L("Permissions") + " - " + Model.User.UserName))

<div class="modal-body">
    @await Html.PartialAsync("~/Areas/App/Views/Common/_PermissionTree.cshtml", Model)
    
    <div class="note note-warning" style="margin-bottom: 0; margin-top: 15px">
        <em>@L("Note_RefreshPageForPermissionChanges")</em>
    </div>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-secondary pull-left reset-permissions-button" data-bs-toggle="tooltip" title="@L("ResetPermissionsTooltip")" data-bs-placement="top"><span>@L("ResetSpecialPermissions")</span></button>
    <button type="button" class="btn btn-light-primary fw-bold close-button" data-bs-dismiss="modal">@L("Cancel")</button>
    <button type="button" class="btn btn-primary save-button"><i class="fa fa-save"></i> <span>@L("Save")</span></button>
</div>